//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PerpusAppWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class buku
    {
        public int id_buku { get; set; }
        public string nama_buku { get; set; }
        public Nullable<int> id_kategori { get; set; }
        public Nullable<int> id_penulis { get; set; }
        public Nullable<int> id_penerbit { get; set; }
        public string halaman { get; set; }
    
        public virtual kategori kategori { get; set; }
        public virtual penerbit penerbit { get; set; }
        public virtual penulis penuli { get; set; }
    }
}
