//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PerpusAppWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class kembalikanbuku
    {
        public int id_kembalikanbuku { get; set; }
        public Nullable<int> id_member { get; set; }
        public string buku { get; set; }
        public Nullable<System.DateTime> tgl_kembali { get; set; }
        public Nullable<int> lamapinjam { get; set; }
        public Nullable<int> denda { get; set; }
    }
}
