//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PerpusAppWeb.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbperpuswebEntities : DbContext
    {
        public dbperpuswebEntities()
            : base("name=dbperpuswebEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<kategori> kategoris { get; set; }
        public virtual DbSet<penerbit> penerbits { get; set; }
        public virtual DbSet<penulis> penulis1 { get; set; }
        public virtual DbSet<member> members { get; set; }
        public virtual DbSet<buku> bukus { get; set; }
        public virtual DbSet<pinjambuku> pinjambukus { get; set; }
        public virtual DbSet<kembalikanbuku> kembalikanbukus { get; set; }
    }
}
