//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PerpusAppWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pinjambuku
    {
        public int id_pinjam { get; set; }
        public Nullable<int> id_member { get; set; }
        public string id_buku { get; set; }
        public Nullable<System.DateTime> tgl_pinjam { get; set; }
        public System.DateTime tgl_kembali { get; set; }
    }
}
